### ISSUE TITLE
Change license to LGPL or more liberal ?

### ISSUE THREAD

**Issue by sfermigier** [scaleway/postal-address#13]
Do you have any particular reason to use the GPL ? We'd like to use your library in a LGPL projet, it would be great if you could change to something more liberal.

**Comment by kdeldycke** [comment]
Well, all our other Python packages are distributed under a BSD 2-Clause license. See https://github.com/scaleway/port-range for instance.

The GPL is a left-over of early internal licensing debates. I'll check with the team but I do not see any strong rational against aligning all our projects to BSD.

**Comment by kdeldycke** [comment]
It's a done deal, we're switching to BSD 2-Clause license then. Working on it. Expect a new release today.

**Comment by kdeldycke** [comment]
`postal-address` 0.9.0 has been released with a BSD license: https://pypi.python.org/pypi/postal-address/0.9.0

**Comment by sfermigier** [comment]
Thanks @kdeldycke !
