### ISSUE TITLE
Add sphinx-based documentation

### ISSUE THREAD

**Issue by moshir** [scaleway/postal-address#14]
Where can i find documentation about this package API ?

**Comment by kdeldycke** [comment]
There's no API doc *per-se* for the moment. You'll have to skim through the code to get some context.

Best things to tackle this issue is to add sphinx-based documentation and host it on readthedocs.com . I've rename this issue accordingly.

**Comment by jak2030** [comment]
Was going to post the same issue. Even a simple getting started section in the readme would be amazing.
