### ISSUE TITLE
Fix hard-requirement of Faker

### ISSUE THREAD

**Issue by frivoire** [scaleway/postal-address#20]
We have been forced to avoid version 0.8.4 of Faker in this commit : https://github.com/scaleway/postal-address/commit/3c9cedf69c35c1391b644442cb76e66d42067432

But we should try to make postal-address works with the latest faker package.

**Comment by frivoire** [comment]
I've researched a little bit (a git bisect on Faker).
==> the commit in `Faker` that broke test of postal-address is : https://github.com/joke2k/faker/commit/5a7e2a4823581f56ba409961126bf1766628aa74

And the error is :
```
ERROR: postal_address.tests.test_address:TestAddressIO.test_random_address
  vi +308 postal_address/tests/test_address.py  # test_random_address
    address = random_address()
  vi +541 postal_address/address.py  # random_address
    subdiv_codes = list(territory_children_codes(components['country_code']))
  vi +204 postal_address/territory.py  # territory_children_codes
    code = normalize_territory_code(territory_code)
  vi +141 postal_address/territory.py  # normalize_territory_code
    'Unrecognized {!r} territory code.'.format(territory_code))
ValueError: Unrecognized u'+970' territory code.
```

**Comment by frivoire** [comment]
I've committed an exclusion of `ar_PS` + removal of hard-requirement of Faker : https://github.com/scaleway/postal-address/commit/45a0dd8af3d4e4010bcb15cbf38dddbe65a2f791

**Comment by kdeldycke** [comment]
LGTM, let's release! :)
